### ISSUE TITLE
Enhance and validate using Hooks

### ISSUE THREAD

**Issue by aeneasr** [ory/hive#12]
Hooks are synchronous events that are executed:

- After successful authentication, before issuing the session
- After successful registration, before issuing the session

Hooks can:

- Modify the session (e.g. adding custom session claims)
- Enrich identities (e.g. fetching active "subscription plans" from Stripe and adding that to the identity / session) - the result will update the identity model in the store
- Intervene in the flow by redirecting to another endpoint (e.g. terms of service changed, please accept before continuing). The authentication should be continued after that.
- Deny the session (e.g. the user canceled their plan via stripe)

Hooks work:

By sending a synchronous HTTP request to the preconfigured hook_url with payload:

and expecting response:

**200** (login ok)

```
{
  session: <- modifies the session
  identity: <- modifies the identity
  redirect_to: <- asks hive to redirect the user to this endpoint
}
```

**403** (login denied)

```
{
  error: <- a reason why the request was not allowed
}
```

**Comment by aeneasr** [comment]
Hive should come with some default hooks. It should generally be possible to chain hooks, like middleware:

```yaml
sign-up:
  hooks:
    - name: Account Activation
       type: account_activation
       config:
         method: email
         field: email
    - id: check stripe
      type: http
      config:
        url: ...
```
