### ISSUE TITLE
hook: Account Activation and Email Verification

### ISSUE THREAD

**Issue by aeneasr** [ory/hive#15]
The account activation hook is executed after sign up and should:

- Send an email containing a TOTP
- Expect the TOTP to be returned in a form field or as a hyper link

The hook should be able to (dis-)allow the issuance of a session after sign up. Default is that no session is created after sign up when the hook is active.

```yaml
name: Account Activation
strategy: account_activation
config:
   reject_session: true
   via: email # phone, whatsapp, ...
```

**challenges**
Identifying if an (e.g. email) is verified or not requires fields `is_verified` as well as the field that is being verified, e.g. `email` or `phone`. This in turn requires the schema to include those fields which limits the applicability of this feature.

Another question is how this would work with multiple emails. Assuming you can add emails to your account later on, those too need to be activated/verified. Maybe account activation uses (internally) A "verification" API which can also be used to verify other emails/phones.
