### ISSUE TITLE
auth: SSI should be able to set verified fields

### ISSUE THREAD

**Issue by aeneasr** [ory/hive#20]
It should be possible to set verified contact identifiers (email, address) automatically by checking the single sign in provider (e.g. Google). Because this can be generic it might be necessary to make this configurable:

```yaml
ssi:
  verify:
  - identifier: path.to.email
    is_verified: path.to.is_verified
    type: email
```
